steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['clean', 'package']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/recommendation:v2', '.']
images: ['gcr.io/$PROJECT_ID/recommendation:v2']
