apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRole
metadata:
  name: recommendation-viewer
  namespace: tutorial
spec:
  rules:
  - services: ["recommendation.tutorial.svc.cluster.local"]
    methods: ["GET"]
---
apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRoleBinding
metadata:
  name: bind-recommendation-viewer
  namespace: tutorial
spec:
  subjects:
  - user: "cluster.local/ns/tutorial/sa/preference"
  roleRef:
    kind: ServiceRole
    name: "recommendation-viewer"
